### PR TITLE
Enabled editing of link picker

### PR DESCRIPTION
**Pull request by zell71**
Hi Karl, 
i've added in the dialog controller and template and added the ability to edit the link picker.
i pass in the target and in the dialogs/linkpicker.controller.js i check if target is not null and then map the model back into the view to allow editing of the controller.
additionally i added a hash target in there as i had a requirement to add that field in for the project i'm working on.  so example: home node is selected but you want to add a hash into the url, you just set the hash.

any questions, ping me a message on twitter (@zell71) or email: dave.ivan.jones@gmail.com

cheers,

### CODE REVIEW

**Comment by karltynan** [comment]
Nice #h5yr - I will check this and see how it aligns with my intentions for the package.

**Comment by zell71** [comment]
No worries - defo needs the edit function as there is no way to check what's set.  Drop the hash target if u want, I only added it as a client wanted to define a hash .

Cheers

**Comment by joshua-stewart** [comment]
When will this update be merged and released? It is the last piece of the puzzle to make Link Picker our default picker in all our Umbraco projects.

**Comment by JimBobSquarePants** [comment]
Just gently nudging this thread to see if we can get the PR merged.

**Comment by karltynan** [comment]
Sorry about the delay! No merged... #h5yr

**Comment by JimBobSquarePants** [comment]
Excellent! :+1:

**Pull request merged**
