### PR TITLE
Add model and property value converter

### PR DESCRIPTION
**Pull request by bjarnef**
Added property value converter for LinkPicker.

### CODE REVIEW

**Comment by karltynan** [comment]
Looks great, thanks!

**Comment by bjarnef** [comment]
Any change you can create a new release with a dll which include tur model and property value converter?

**Comment by karltynan** [comment]
Yes, sorry I have been away - I need to get it sorted for Our and Nuget and release it ASAP.

**Comment by bjarnef** [comment]
Thanks.
Btw. you can add the link to the NuGet package on our.umbraco.org, so it is more clear and consistent when packages have an NuGet package: https://our.umbraco.org/projects/backoffice-extensions/link-picker/

**Comment by bjarnef** [comment]
Any update on when a new release with be available?
I will prefer to use this from the package instead of adding my own model and property value converter.

**Comment by karltynan** [comment]
Sorry. I'm just waiting on some assistance from a co-worker on getting it setup for deployment to Nuget/Our.

**Pull request merged**
